name: MiniGame Generator

on:
  schedule:
    - cron: '0 1 * * *' # jalan setiap jam 1 pagi UTC (08.00 WIB)
  workflow_dispatch:     # bisa dijalankan manual juga

jobs:
  generate-minigame:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Minigame Result
        run: |
          echo "C. Python — Bahasa ini identik dengan Data Science & AI 🧠" > game-result.txt

      - name: Commit & Push Result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add game-result.txt
          git commit -m "🎮 Update minigame result"
          git push